### ISSUE TITLE
Identify the ABCI request type

### ISSUE THREAD

**Issue by atuleu** [multiverseHQ/abci_proxy#2]
I think the first steps would be to set up the list of ABCI protocol request and responses that should end up in one of the two categories:

* Should directly be pass-by and forth between the tendermint and the target client app
* Should be intercepted and managed by the ABCi1ClickDeploy interface

**Comment by antoineherzog** [comment]
the one to be intercept is the EndBlock method where we can update the set of validators
you check the documention here:
https://github.com/tendermint/abci
