### ISSUE TITLE
Repository structure organisation

### ISSUE THREAD

**Issue by atuleu** [multiverseHQ/abci_proxy#3]
Usually in golang, one would prefer to put the code for the ABCi proxy on the top level directory and the source code for the CLI application in a subdirectory.

This encourages reuse of the proxy code in other application, by letting it have a smaller path. The CLI, is just the instantation of the proxy in an simple executable.

**Comment by antoineherzog** [comment]
@atuleu that's my fault because i am new to Golang

**Comment by antoineherzog** [comment]
i agree with you

**Comment by atuleu** [comment]
corrected with #4
